// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALpTPLsNx6Ma_TD9CB80NKbI833iYA2nQ',
    appId: '1:419070017648:web:fe662639e7c47294b374b5',
    messagingSenderId: '419070017648',
    projectId: 'comfortpg-3f724',
    authDomain: 'comfortpg-3f724.firebaseapp.com',
    storageBucket: 'comfortpg-3f724.firebasestorage.app',
    measurementId: 'G-F0K4DVE1F0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLhx2-acnLkqwaXwweNhaBm6CKQVfNEnc',
    appId: '1:419070017648:android:c796a3c3d87e724cb374b5',
    messagingSenderId: '419070017648',
    projectId: 'comfortpg-3f724',
    storageBucket: 'comfortpg-3f724.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMbTN8ubeFaA0kPrKmjo_ENxIG2nar7FQ',
    appId: '1:419070017648:ios:3830a4f3e29cb56db374b5',
    messagingSenderId: '419070017648',
    projectId: 'comfortpg-3f724',
    storageBucket: 'comfortpg-3f724.firebasestorage.app',
    iosBundleId: 'com.example.hostelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMbTN8ubeFaA0kPrKmjo_ENxIG2nar7FQ',
    appId: '1:419070017648:ios:3830a4f3e29cb56db374b5',
    messagingSenderId: '419070017648',
    projectId: 'comfortpg-3f724',
    storageBucket: 'comfortpg-3f724.firebasestorage.app',
    iosBundleId: 'com.example.hostelapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALpTPLsNx6Ma_TD9CB80NKbI833iYA2nQ',
    appId: '1:419070017648:web:26ed0de3f36254ccb374b5',
    messagingSenderId: '419070017648',
    projectId: 'comfortpg-3f724',
    authDomain: 'comfortpg-3f724.firebaseapp.com',
    storageBucket: 'comfortpg-3f724.firebasestorage.app',
    measurementId: 'G-QTMMTVR4F0',
  );
}
